apiVersion: v1
kind: Namespace
metadata:
  name: apps

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: goappserver
  name: goappserver
  namespace: apps
spec:
  selector:
    matchLabels:
      app: goappserver
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: goappserver
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: goappserver
          image: babbili/k8s-envoylb-goappserver:6aea9c1d
          imagePullPolicy : Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            privileged: false
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          ports:
          - containerPort: 50051
      serviceAccount: goappserver
      serviceAccountName: goappserver

---

apiVersion: v1
kind: Service
metadata:
  name: goappserver
  namespace: apps
  labels:
    app: goappserver
spec:
  type: ClusterIP
  selector:
    app: goappserver
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: goappserver
  name: goappserver
  namespace: apps

---

apiVersion: v1
kind: Secret
metadata:
  name: goappserver-svca-token
  namespace: apps
  annotations:
    kubernetes.io/service-account.name: "goappserver"
type: kubernetes.io/service-account-token
