// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: apps.proto

package k8s_envoylb_cilium

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoappClient is the client API for Goapp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoappClient interface {
	CreateNewUser(ctx context.Context, in *NewUser, opts ...grpc.CallOption) (*User, error)
}

type goappClient struct {
	cc grpc.ClientConnInterface
}

func NewGoappClient(cc grpc.ClientConnInterface) GoappClient {
	return &goappClient{cc}
}

func (c *goappClient) CreateNewUser(ctx context.Context, in *NewUser, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/protos.Goapp/CreateNewUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoappServer is the server API for Goapp service.
// All implementations must embed UnimplementedGoappServer
// for forward compatibility
type GoappServer interface {
	CreateNewUser(context.Context, *NewUser) (*User, error)
	mustEmbedUnimplementedGoappServer()
}

// UnimplementedGoappServer must be embedded to have forward compatible implementations.
type UnimplementedGoappServer struct {
}

func (UnimplementedGoappServer) CreateNewUser(context.Context, *NewUser) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewUser not implemented")
}
func (UnimplementedGoappServer) mustEmbedUnimplementedGoappServer() {}

// UnsafeGoappServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoappServer will
// result in compilation errors.
type UnsafeGoappServer interface {
	mustEmbedUnimplementedGoappServer()
}

func RegisterGoappServer(s grpc.ServiceRegistrar, srv GoappServer) {
	s.RegisterService(&Goapp_ServiceDesc, srv)
}

func _Goapp_CreateNewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoappServer).CreateNewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Goapp/CreateNewUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoappServer).CreateNewUser(ctx, req.(*NewUser))
	}
	return interceptor(ctx, in, info, handler)
}

// Goapp_ServiceDesc is the grpc.ServiceDesc for Goapp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Goapp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Goapp",
	HandlerType: (*GoappServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNewUser",
			Handler:    _Goapp_CreateNewUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps.proto",
}
